//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodingExercise.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodingExercise.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Day&quot;:1,&quot;Number&quot;:1,&quot;Departure&quot;:&quot;YUL&quot;,&quot;Arrival&quot;:&quot;YYZ&quot;},{&quot;Day&quot;:1,&quot;Number&quot;:2,&quot;Departure&quot;:&quot;YUL&quot;,&quot;Arrival&quot;:&quot;YYC&quot;},{&quot;Day&quot;:1,&quot;Number&quot;:3,&quot;Departure&quot;:&quot;YUL&quot;,&quot;Arrival&quot;:&quot;YVR&quot;},{&quot;Day&quot;:2,&quot;Number&quot;:4,&quot;Departure&quot;:&quot;YUL&quot;,&quot;Arrival&quot;:&quot;YYZ&quot;},{&quot;Day&quot;:2,&quot;Number&quot;:5,&quot;Departure&quot;:&quot;YUL&quot;,&quot;Arrival&quot;:&quot;YYC&quot;},{&quot;Day&quot;:2,&quot;Number&quot;:6,&quot;Departure&quot;:&quot;YUL&quot;,&quot;Arrival&quot;:&quot;YVR&quot;}].
        /// </summary>
        internal static string Flights {
            get {
                return ResourceManager.GetString("Flights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;order-001&quot;: {
        ///        &quot;destination&quot; : &quot;YYZ&quot;
        ///    },
        ///    &quot;order-002&quot;: {
        ///        &quot;destination&quot; : &quot;YYZ&quot;
        ///    },
        ///    &quot;order-003&quot;: {
        ///        &quot;destination&quot; : &quot;YYZ&quot;
        ///    },
        ///    &quot;order-004&quot;: {
        ///        &quot;destination&quot; : &quot;YYZ&quot;
        ///    },
        ///    &quot;order-005&quot;: {
        ///        &quot;destination&quot; : &quot;YYZ&quot;
        ///    },&quot;order-006&quot;: {
        ///        &quot;destination&quot; : &quot;YYZ&quot;
        ///    },&quot;order-007&quot;: {
        ///        &quot;destination&quot; : &quot;YYZ&quot;
        ///    },&quot;order-008&quot;: {
        ///        &quot;destination&quot; : &quot;YYZ&quot;
        ///    },&quot;order-009&quot;: {
        ///        &quot;destination&quot; : &quot;YYZ&quot;
        ///    },&quot;order-010&quot;: {
        ///        &quot;des [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
    }
}
